// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t dynamic_biases[8] = {-2104, 3918, 6203, -4033, -5266, 4664, -5067, -3236};
