// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#define DYNAMIC_OUT_CH 8
#define DYNAMIC_IN_CH 3
#define DYNAMIC_INPUT_W 3
#define DYNAMIC_INPUT_H 3
#define DYNAMIC_DST_SIZE 72
#define DYNAMIC_INPUT_SIZE 27
#define DYNAMIC_OUT_ACTIVATION_MIN -128
#define DYNAMIC_OUT_ACTIVATION_MAX 127
#define DYNAMIC_INPUT_BATCHES 1
#define DYNAMIC_FILTER_X 3
#define DYNAMIC_FILTER_Y 3
#define DYNAMIC_STRIDE_X 1
#define DYNAMIC_STRIDE_Y 1
#define DYNAMIC_PAD_X 1
#define DYNAMIC_PAD_Y 1
#define DYNAMIC_OUTPUT_W 3
#define DYNAMIC_OUTPUT_H 3
#define DYNAMIC_INPUT_OFFSET 1
#define DYNAMIC_OUTPUT_OFFSET 0
#define DYNAMIC_DILATION_X 1
#define DYNAMIC_DILATION_Y 1
