// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t dynamic_input[27] = {-124, 40,  -10, -9,   -5,  -9,   -102, 7,   119, 30,  -66, -117, 71, 67,
                                  124,  114, 33,  -104, -58, -109, 93,   -97, 99,  -17, 39,  -40,  33};
