// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t dynamic_output_mult[8] =
    {1813154944, 1158404608, 1208770048, 1712424192, 1561328000, 2115347584, 1259135488, 1158404608};
