// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t dynamic_output_ref[72] = {-4,  0,    39,  -34, 32,  8,   -17, 20, -12, 22, -72, -46, 36,  -10, -32,
                                       -68, -2,   -36, -14, -58, 36,  43,  -7, 24,  -2, 51,  4,   -21, -29, 4,
                                       16,  -125, 51,  104, 73,  -11, -92, 28, 122, 31, 3,   -64, 61,  -3,  -80,
                                       -23, -83,  2,   -4,  39,  25,  -24, 6,  11,  19, 7,   12,  -85, 27,  -23,
                                       -2,  6,    -28, 37,  -41, 56,  -31, 45, 30,  8,  -60, -42};
